import { AppError, requireCondition } from './errors.js';
import { parse, type Schema } from '../contracts/parse.js';
import type * as v from 'valibot';
const encoder = new TextEncoder();
export function b64(bytes: Uint8Array): string {
  let binary = ''; for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
export function unb64(text: string): Uint8Array<ArrayBuffer> {
  requireCondition(/^[A-Za-z0-9_-]+$/.test(text) && text.length % 4 !== 1, 400, 'BAD_INPUT', 'Invalid encoding.');
  try { return Uint8Array.from(atob(text.replace(/-/g, '+').replace(/_/g, '/')), c => c.charCodeAt(0)); }
  catch { throw new AppError(400, 'BAD_INPUT', 'Invalid encoding.'); }
}
export function random(): string { return b64(crypto.getRandomValues(new Uint8Array(32))); }
export async function hash(value: string): Promise<string> { return b64(new Uint8Array(await crypto.subtle.digest('SHA-256', encoder.encode(value)))); }
export async function sha1(value: string): Promise<string> { return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-1', encoder.encode(value))), n => n.toString(16).padStart(2, '0')).join(''); }
export function equal(a: string, b: string): boolean {
  const aa = encoder.encode(a), bb = encoder.encode(b); let delta = aa.length ^ bb.length;
  for (let i = 0; i < Math.max(aa.length, bb.length); i++) delta |= (aa[i] || 0) ^ (bb[i] || 0);
  return delta === 0;
}
const aesKeys=new Map<string,Promise<CryptoKey>>();
const rsaKeys=new Map<string,Promise<CryptoKey>>();
function keyOnce(cache:Map<string,Promise<CryptoKey>>,identity:string,create:()=>Promise<CryptoKey>):Promise<CryptoKey>{
  const existing=cache.get(identity);if(existing)return existing;
  if(cache.size>=4)cache.delete(cache.keys().next().value!);
  const pending=create();cache.set(identity,pending);
  void pending.catch(()=>{if(cache.get(identity)===pending)cache.delete(identity);});
  return pending;
}
async function aesKey(secret: string): Promise<CryptoKey> {
  const bytes = unb64(secret);
  requireCondition(bytes.length === 32 && b64(bytes) === secret, 503, 'CONFIGURATION', 'SESSION_SECRET must encode 32 random bytes.');
  return keyOnce(aesKeys,secret,()=>crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['encrypt','decrypt']));
}
export async function encrypt(value: unknown, secret: string, purpose: string): Promise<string> {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ciphertext = await crypto.subtle.encrypt({ name: 'AES-GCM', iv, additionalData: encoder.encode('giscus:v2:' + purpose) }, await aesKey(secret), encoder.encode(JSON.stringify(value)));
  return `2.${b64(iv)}.${b64(new Uint8Array(ciphertext))}`;
}
export async function decrypt<S extends Schema>(schema: S, text: string, secret: string, purpose: string): Promise<v.InferOutput<S>> {
  let value: unknown;
  try {
    const [version, nonce, body, extra] = text.split('.');
    if (version !== '2' || !nonce || !body || extra || unb64(nonce).length !== 12) throw new Error('envelope');
    const bytes = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: unb64(nonce), additionalData: encoder.encode('giscus:v2:' + purpose) }, await aesKey(secret), unb64(body));
    value = JSON.parse(new TextDecoder('utf-8', { fatal: true, ignoreBOM: false }).decode(bytes)) as unknown;
  } catch { throw new AppError(503, 'STORAGE', 'The service could not decrypt a stored record.'); }
  return parse(schema, value, 'storage');
}
function der(tag: number, bytes: Uint8Array): Uint8Array<ArrayBuffer> {
  const sizes: number[] = []; let length = bytes.length;
  if (length < 128) sizes.push(length);
  else { while (length) { sizes.unshift(length & 255); length >>>= 8; } sizes.unshift(128 | sizes.length); }
  return new Uint8Array([tag, ...sizes, ...bytes]);
}
export function pkcs8(pem: string): Uint8Array<ArrayBuffer> {
  const match = /^-----BEGIN (RSA PRIVATE KEY|PRIVATE KEY)-----\s*([A-Za-z0-9+/=\s]+)-----END \1-----$/.exec(pem.replace(/\\n/g, '\n').trim());
  requireCondition(match?.[2], 503, 'CONFIGURATION', 'Use the unencrypted RSA private key generated by GitHub.');
  let bytes: Uint8Array<ArrayBuffer>;
  try { bytes = Uint8Array.from(atob(match[2].replace(/\s/g, '')), c => c.charCodeAt(0)); }
  catch { throw new AppError(503, 'CONFIGURATION', 'Invalid RSA key encoding.'); }
  if (match[1] === 'PRIVATE KEY') return bytes;
  return der(0x30, new Uint8Array([2, 1, 0, 0x30, 0x0d, 6, 9, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 1, 1, 1, 5, 0, ...der(4, bytes)]));
}
export async function appJWT(appId: string, pem: string, now: number): Promise<string> {
  const seconds = Math.floor(now / 1000);
  const text = `${b64(encoder.encode('{"alg":"RS256","typ":"JWT"}'))}.${b64(encoder.encode(JSON.stringify({ iss: appId, iat: seconds - 60, exp: seconds + 540 })))}`;
  const key=await keyOnce(rsaKeys,pem,()=>crypto.subtle.importKey('pkcs8',pkcs8(pem),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']));
  return `${text}.${b64(new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5', key, encoder.encode(text))))}`;
}
