import * as v from 'valibot';
import * as R from './requests.js';
import { Capability, EmptyCapability, RepositoryName } from './primitives.js';
export const ThreadCall = v.strictObject({ request: R.ThreadRequest, session: v.optional(EmptyCapability, '') });
export const RepliesCall = v.strictObject({ request: R.RepliesRequest, session: v.optional(EmptyCapability, '') });
export const CommentCall = v.strictObject({ request: R.CommentRequest, session: Capability });
export const EditCall = v.strictObject({ request: R.EditRequest, session: Capability });
export const DeleteCall = v.strictObject({ request: R.DeleteRequest, session: Capability });
export const ReactionCall = v.strictObject({ request: R.ReactionRequest, session: Capability });
export const ModerateCall = v.strictObject({ request: R.ModerateRequest, session: Capability });
export const PreviewCall = v.strictObject({ request: R.PreviewRequest, session: Capability });
export const InfoCall = R.InfoRequest;
export const PrepareCall = v.strictObject({ request: R.AuthPrepare, browserCookie: Capability });
export const CallbackCall = v.strictObject({ repo: RepositoryName, attempt: Capability, browserCookie: EmptyCapability, code: v.optional(v.pipe(v.string(), v.maxLength(1024)), ''), denied: v.boolean() });
export const PollCall = R.AuthProof;
export const ConsumeCall = R.AuthConsume;
export const LogoutCall = v.strictObject({ request: R.LogoutRequest, session: Capability });
export type ThreadCall = v.InferOutput<typeof ThreadCall>;
export type RepliesCall = v.InferOutput<typeof RepliesCall>;
export type CommentCall = v.InferOutput<typeof CommentCall>;
export type EditCall = v.InferOutput<typeof EditCall>;
export type DeleteCall = v.InferOutput<typeof DeleteCall>;
export type ReactionCall = v.InferOutput<typeof ReactionCall>;
export type ModerateCall = v.InferOutput<typeof ModerateCall>;
export type PreviewCall = v.InferOutput<typeof PreviewCall>;
export type PrepareCall = v.InferOutput<typeof PrepareCall>;
export type CallbackCall = v.InferOutput<typeof CallbackCall>;
export type LogoutCall = v.InferOutput<typeof LogoutCall>;

export const DiscussionActionCall=v.strictObject({request:R.DiscussionActionRequest,session:Capability});
export const BlockCall=v.strictObject({request:R.BlockRequest,session:Capability});
export type DiscussionActionCall=v.InferOutput<typeof DiscussionActionCall>;
export type BlockCall=v.InferOutput<typeof BlockCall>;
