import octicons from '@primer/octicons';
import {writeFile} from 'node:fs/promises';
const names=['smiley','mark-github','sign-out','typography','kebab-horizontal','markdown','check','reply','fold-up','copy','sync'];
const sources=Object.fromEntries(names.map(name=>[name,octicons[name].toSVG().replace("<svg ","<svg xmlns=\"http://www.w3.org/2000/svg\" ")]));
await writeFile('src/browser/icons.ts',`/** GitHub Octicons, MIT; generated by scripts/generate-icons.mjs. */\nconst icons=${JSON.stringify(sources)} as const;\nexport function icon(name:keyof typeof icons):SVGElement { const node=document.importNode(new DOMParser().parseFromString(icons[name],"image/svg+xml").documentElement,true) as unknown as SVGElement;node.setAttribute("aria-hidden","true");node.setAttribute("focusable","false");node.setAttribute("overflow","visible");node.setAttribute("class","octicon");return node;}\n`);
