import assert from 'node:assert/strict';
import { randomBytes, createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { nativeService } from '../test/native-service.mjs';
import { loadModule } from '../test/modules.mjs';
import { evidence } from '../test/evidence.mjs';
const origin = 'http://127.0.0.1:18790', blog = 'http://127.0.0.1:18791';
const config = { repo: 'example/comments', origin: blog + '/article', term: 'article' };
const random = () => randomBytes(32).toString('base64url'), hash = value => createHash('sha256').update(value).digest('base64url');
const key = () => '3.' + Date.now() + '.' + random();
const report = evidence('native-service-workflows');
const service = await nativeService({ origin, blog });
report.runtime = service.versions;
const read = (name, input, cap = '') => service.fetch(origin + '/api/v4/' + name + '?' + new URLSearchParams({ input: JSON.stringify(input) }), { headers: { Origin: origin, ...(cap ? { Authorization: 'Bearer ' + cap } : {}) } });
const post = (name, input, cap = '', headers = {}) => service.fetch(origin + '/api/v4/' + name, { method: 'POST', headers: { Origin: origin, 'Content-Type': 'application/json', ...(cap ? { Authorization: 'Bearer ' + cap } : {}), ...headers }, body: JSON.stringify(input) });
const json = async (response, status = 200) => { const result = await response.json(); assert.equal(response.status, status, JSON.stringify(result)); return result; };
let signInIndex = 0;
async function signIn(principal = 'reader') {
    const headers = { 'CF-Connecting-IP': '192.0.2.' + (80 + signInIndex++) };
    service.github.oauthUser = principal;
    const cap = random(), proof = hash(cap);
    const prepared = await post('auth/prepare', { repo: config.repo, origin: config.origin, proof, mode: 'popup' }, '', headers);
    const cookie = prepared.headers.get('Set-Cookie')?.split(';')[0], data = await json(prepared), url = new URL(data.authorizeURL);
    assert.equal(data.attempt, hash(proof));
    assert.equal((await read('page', { config }, cap)).status, 401, 'a future capability is unusable before authorization');
    const callback = origin + '/auth/callback?' + new URLSearchParams({ state: url.searchParams.get('state'), code: 'fixture_' + url.searchParams.get('code_challenge') });
    const response = await service.fetch(callback, { headers: { Cookie: cookie, ...headers }, redirect: 'manual' }), html = await response.text();
    assert.equal(response.status, 200, html);
    assert.ok(!html.includes(cap) && !html.includes(proof) && !html.includes('ghu_'), 'callback contains no credential or capability');
    assert.equal((await service.fetch(callback, { headers: { Cookie: cookie, ...headers }, redirect: 'manual' })).status, 401, 'authorization is one-use');
    assert.equal((await post('auth/prepare', { repo: config.repo, origin: config.origin, proof, mode: 'popup' }, '', headers)).status, 409, 'an existing future capability cannot be replaced');
    return cap;
}
const contribute = (action, cap, submission = key()) => post('contribute', { config, key: submission, action }, cap);
try {
    const first = service.github.discussions[0].comments[0];
    first.body = 'hello🌿'.repeat(32768);
    const response = await read('page', { config }), page = await json(response);
    assert.equal(page.window.total, service.github.discussions[0].comments.length);
    assert.equal(page.nodes[first.id].body, first.body, 'native serialization preserves large Unicode values');
    assert.ok(Number(response.headers.get('X-Giscusflare-Expires')) > Date.now());
    const withoutPrefetch = await json(await read('page', { config, replyPrefetch: 0 }));
    assert.deepEqual(withoutPrefetch.replies[first.id].ids, [], 'zero reply prefetch leaves the child window unobserved');
    assert.equal(withoutPrefetch.replies[first.id].total, first.replies.length);
    assert.notEqual(withoutPrefetch.replies[first.id].cursor, null, 'real replies remain discoverable without prefetch');
    const replies = await json(await read('page', { config, parentId: first.id }));
    assert.equal(replies.window.total, first.replies.length);
    assert.deepEqual(replies.window.ids.map(id => replies.nodes[id].body), first.replies.map(reply => reply.body));
    const widget = '/widget?' + new URLSearchParams(config);
    assert.equal((await service.fetch(origin + widget)).status, 200);
    const calls = service.github.calls.length, hit = await service.fetch(origin + widget);
    assert.equal(hit.status, 200);
    assert.equal(hit.headers.get('Cache-Control'), 'no-store');
    assert.ok(hit.headers.get('Content-Security-Policy').includes(blog));
    assert.equal(service.github.calls.length, calls, 'server bootstrap cache avoids repeated provider work');
    assert.equal((await read('page', { config: { ...config, origin: 'https://unapproved.example/' } })).status, 403);
    report.checks.push({ workflow: 'read useful root/reply windows through native RPC, frame/cache and origin boundaries', status: 'passed' });
    const cap = await signIn();
    const creation = { type: 'comment', body: 'A native contribution' }, submission = key();
    const providerFetch = service.github.fetch.bind(service.github);
    service.github.fetch = async request => {
        const query = request.method === 'POST' ? (await request.clone().json()).query : '';
        const response = await providerFetch(request);
        if (query?.startsWith('mutation')) { service.github.failNext = 503; service.github.fetch = providerFetch; }
        return response;
    };
    const ack = await json(await post('contribute', { config, key: submission, action: creation, html: true }, cap));
    assert.equal(ack.patch, undefined, 'a failed observation cannot reopen a confirmed external effect');
    const htmlReplay = await json(await post('contribute', { config, key: submission, action: creation, html: true }, cap));
    assert.ok(htmlReplay.patch.nodes[ack.id].bodyHTML.includes(creation.body), 'A confirmed receipt can observe requested provider HTML');
    const replay = await json(await post('contribute', { config, key: submission, action: creation, html: false }, cap));
    assert.equal(replay.id, ack.id, 'Changing content presentation retains the confirmed contribution');
    assert.equal(replay.patch.nodes[ack.id].body, creation.body, 'receipt replay observes current content without another effect');
    assert.equal(replay.patch.nodes[ack.id].bodyHTML, undefined, 'A Markdown consumer can recover the same receipt without provider HTML');
    const discussion = service.github.discussions[0], root = discussion.comments.find(comment => comment.id === ack.id);
    assert.equal(discussion.comments.filter(comment => comment.body === creation.body).length, 1, 'receipt replay has one external effect');
    const reply = await json(await contribute({ type: 'comment', body: 'A native reply', replyToId: ack.id }, cap));
    assert.equal(root.replies.find(comment => comment.id === reply.id)?.body, 'A native reply');
    await json(await contribute({ type: 'edit', id: ack.id, body: 'Revised contribution' }, cap));
    assert.equal(root.body, 'Revised contribution');
    await json(await contribute({ type: 'reaction', id: ack.id, reaction: 'HEART', add: true }, cap));
    assert.ok(root.votes.HEART.includes('reader'));
    const moderator = await signIn('maintainer');
    await json(await contribute({ type: 'moderate', id: ack.id, minimized: true, reason: 'OFF_TOPIC' }, moderator));
    assert.equal(root.isMinimized, true);
    await json(await contribute({ type: 'moderate', id: ack.id, minimized: false }, moderator));
    await json(await contribute({ type: 'delete', id: reply.id }, cap));
    assert.equal(root.replies.length, 0);
    const readback = await json(await read('page', { config }, cap));
    assert.equal(readback.window.total, discussion.comments.length);
    assert.equal((await json(await read('page', { config, ids: [ack.id] }, cap))).nodes[ack.id].body, 'Revised contribution');
    assert.equal((await json(await read('counts', { repo: config.repo, origin: config.origin, strict: false, terms: ['article', 'missing'] }))).counts.article, discussion.comments.length);
    report.checks.push({ workflow: 'authorize a future capability, contribute/replay, edit, reply, react, moderate and remove with independent provider effects', status: 'passed' });
    const uncertain = { type: 'comment', body: 'Committed before the connection was lost' }, uncertainKey = key();
    service.github.failAfterMutation = true;
    assert.equal((await json(await contribute(uncertain, cap, uncertainKey), 502)).error.code, 'WRITE_UNCERTAIN');
    await service.restart();
    assert.equal((await json(await read('page', { config }, cap))).metadata.viewer.login, 'reader');
    assert.equal((await json(await contribute(uncertain, cap, uncertainKey), 409)).error.code, 'WRITE_UNCERTAIN');
    service.github.setLogin('reader', 'renamed-reader');
    const renamed = cap;
    assert.equal((await json(await read('page', { config, ids: [ack.id] }, cap))).metadata.viewer.login, 'renamed-reader', 'fresh Page display is observed from GitHub without reissuing the capability');
    assert.equal((await json(await contribute(uncertain, renamed, uncertainKey), 409)).error.code, 'WRITE_UNCERTAIN');
    service.github.setLogin('visitor', 'reader');
    const other = await signIn('visitor');
    assert.equal((await json(await contribute(uncertain, other, uncertainKey), 409)).error.code, 'CONFLICT');
    assert.equal(discussion.comments.filter(comment => comment.body === uncertain.body).length, 1);
    const { PageModel } = await loadModule('src/conversation/page.ts');
    let clientIdentity = { capability: renamed, id: 'U_reader' };
    const issuedRequests = [];
    const transport = {
        get principal() { return clientIdentity.id; },
        async request(operation, input, _signal, method = 'GET') {
            if (operation === 'contribute') issuedRequests.push(input);
            const response = await (method === 'POST' ? post(operation, input, clientIdentity.capability) : read(operation, input, clientIdentity.capability));
            const value = await response.json();
            if (!response.ok) throw Object.assign(new Error(value.error.message), value.error, { status: response.status });
            return value;
        },
    };
    const client = new PageModel(config, transport); await client.start(); await client.loadMore();
    const writing = client.writing({ kind: 'reply', id: ack.id }).show();
    writing.update('Recovered reply belongs to the immutable original author');
    service.github.failAfterMutation = true;
    assert.equal((await writing.submit()).status, 'failed');
    assert.equal(writing.error.status, 'uncertain');
    writing.hide(); const savedWriting = client.saveWriting(); client.lifetime.abort();
    const restored = new PageModel(config, transport); restored.recoverWriting(savedWriting); await restored.start();
    const recovered = restored.writing({ kind: 'reply', id: ack.id });
    assert.equal((await recovered.submit()).status, 'blocked', 'Restored closed writing remains closed');
    recovered.show(); clientIdentity = { capability: other, id: 'U_visitor' }; restored.changeIdentity(); await restored.start();
    assert.equal((await recovered.submit()).status, 'blocked', 'An account with the former author login cannot recover that author writing');
    assert.equal(recovered.actions.clear, false, 'Changing accounts cannot discard an unresolved issuance');
    clientIdentity = { capability: renamed, id: 'U_reader' }; restored.changeIdentity(); await restored.start();
    assert.equal(recovered.actions.retry, true, 'The renamed original author can recover writing');
    await recovered.submit();
    assert.equal(recovered.error.status, 'uncertain', 'An ambiguous provider receipt stays visible through recovery');
    assert.equal(issuedRequests.at(-1).key, issuedRequests[0].key, 'Restored writing retains the original receipt identity');
    assert.equal(root.replies.filter(reply => reply.body === recovered.text).length, 1, 'Client recovery never changes a reply into a root or duplicates its provider effect');
    assert.equal(discussion.comments.some(comment => comment.body === recovered.text), false);
    assert.equal(recovered.abandon(), true, 'The original author can explicitly reconcile an unresolved submission');
    assert.equal(recovered.target.id, ack.id); assert.equal(recovered.actions.edit, true);
    service.github.failAfterMutation = true;
    await restored.setReaction(first.id, 'LAUGH', true).catch(() => {});
    const reactionIssuance = issuedRequests.at(-1);
    assert.equal(restored.actions(first.id).react.status, 'recovery');
    clientIdentity = { capability: 'x'.repeat(43), id: 'U_reader' };
    await restored.retryAction(first.id).catch(() => {});
    assert.equal(restored.actions(first.id).react.status, 'recovery', 'Rejected recovery cannot erase an earlier uncertain effect');
    const recoveryRequests = issuedRequests.length;
    clientIdentity = { capability: other, id: 'U_visitor' }; restored.changeIdentity(); await restored.start();
    await restored.retryAction(first.id).catch(() => {});
    assert.equal(issuedRequests.length, recoveryRequests, 'Another account cannot issue recovery work');
    clientIdentity = { capability: renamed, id: 'U_reader' }; restored.changeIdentity(); await restored.start();
    await restored.retryAction(first.id).catch(() => {});
    assert.deepEqual(issuedRequests.at(-1).action, reactionIssuance.action);
    assert.equal(issuedRequests.at(-1).key, reactionIssuance.key, 'Action recovery preserves the original effect identity');
    assert.equal(first.votes.LAUGH.filter(principal => principal === 'reader').length, 1, 'Uncertain action recovery has one independently observed provider effect');
    assert.equal(restored.abandonAction(first.id), true);
    assert.equal(first.votes.LAUGH.includes('reader'), true, 'Deliberate abandonment releases local recovery without reversing the external effect');
    restored.lifetime.abort();
    report.checks.push({ workflow: 'real client writing recovery retains reply target, immutable author and issued identity through dismissal, reload, account collision, denied recovery and uncertain provider receipts', status: 'passed' });
    await json(await post('logout', { repo: config.repo, origin: config.origin }, renamed));
    assert.equal((await read('page', { config }, renamed)).status, 401);
    report.checks.push({ workflow: 'ambiguous remote commit survives native restart and account rename without replay or ownership transfer; logout revokes', status: 'passed' });
    report.status = 'passed';
}
catch (error) {
    report.status = 'failed';
    report.details = error.stack || String(error);
    process.exitCode = 1;
    console.error(report.details);
}
finally {
    await service.dispose();
    report.completedAt = new Date().toISOString();
    await mkdir('test-results/evidence', { recursive: true });
    await writeFile('test-results/evidence/native-runtime.json', JSON.stringify(report, null, 2) + '\n');
}
